version: '3.9'

services:

  dbDisem:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB=mydatabase: apidisem
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5434'
    volumes:
      - ./data_apiDisem:/var/lib/postgresql/data
