version: '3.9'

services:

  dbDisem:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB=mydatabase: apidisem
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5434'
    volumes:
      - ./data_apiDisem:/var/lib/postgresql/data

  app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://dbDisem:5432/apidisem
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres

        SPRING_MAIL_HOST: smtp.gmail.com
        SPRING_MAIL_PORT: 587
        SPRING_MAIL_USERNAME: wemelly@unifesspa.edu.br
        SPRING_MAIL_PASSWORD: 91090214
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"


      depends_on:
        - dbDisem
