spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}

  minio:
    url: ${MINIO_URL}
    access:
      name: ${MINIO_USER}
      secret: ${MINIO_SECRET}
    bucket:
      name: ${MINIO_BUCKET}

  webservice:
    token:
      url: ${WEB_SERVICE_TOKEN}
    buscarVinculo:
      url: ${WEB_SERVICE_BUSCAR}
    login:
      url: ${WEB_SERVICE_LOGIN}

