spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://18.230.17.37:5432/apidisem
    username: disem
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret-key}

  minio:
    url: http://minio-dev.unifesspa.edu.br:9000
    access:
      name: minio
      secret: shi5ahshu[geFieg
    bucket:
      name: sinfra

  mail:
    host: smtp.gmail.com
    port: 587
    username: wemelly@unifesspa.edu.br
    password: hnekhfenxfhvqyzg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true